SELECT * FROM TEST_MEMBER ;

--

INSERT INTO TEST_MEMBER VALUES(10, '남윤주', SYSDATE);
SELECT * FROM TEST_MEMBER ;

INSERT INTO TEST_MEMBER VALUES(22, '이승환', '1994-02-21');
INSERT INTO TEST_MEMBER VALUES(17, '윤종섭', '2019-08-03');
INSERT INTO TEST_MEMBER VALUES('' ,'이예지','');
--INSERT INTO TEST_MEMBER VALUES(10,'',SYSDATE); --> 이름에 NOTNULL 을 해놓았기 때문에 NULL 값은 안된다
INSERT INTO TEST_MEMBER VALUES(NULL, '문상현', '2017-01-01');


SELECT * FROM  TEST_MEMBER ; -- 비어있는 '' 를 INSERT 하면 NULL 값 처리
-- dBeaver 에서는 기본적으로 auto-comit 수행

SELECT * FROM  TEST_MEMBER;  




